global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:9991', 'host.docker.internal:9992']
