/*
 * This file is generated by jOOQ.
 */

package scrapper.domains.jooq;


import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import scrapper.domains.jooq.tables.LinkSubscription;
import scrapper.domains.jooq.tables.TgUser;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>LINK_SUBSCRIPTION</code>.
     */
    public final LinkSubscription LINK_SUBSCRIPTION = LinkSubscription.LINK_SUBSCRIPTION;

    /**
     * The table <code>TG_USER</code>.
     */
    public final TgUser TG_USER = TgUser.TG_USER;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    @NotNull
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    @NotNull
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            LinkSubscription.LINK_SUBSCRIPTION,
            TgUser.TG_USER
        );
    }
}
