/*
 * This file is generated by jOOQ.
 */

package scrapper.domains.jooq;


import javax.annotation.processing.Generated;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import scrapper.domains.jooq.tables.LinkSubscription;
import scrapper.domains.jooq.tables.TgUser;
import scrapper.domains.jooq.tables.records.LinkSubscriptionRecord;
import scrapper.domains.jooq.tables.records.TgUserRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<LinkSubscriptionRecord> CONSTRAINT_F = Internal.createUniqueKey(LinkSubscription.LINK_SUBSCRIPTION, DSL.name("CONSTRAINT_F"), new TableField[] { LinkSubscription.LINK_SUBSCRIPTION.ID }, true);
    public static final UniqueKey<TgUserRecord> CONSTRAINT_D = Internal.createUniqueKey(TgUser.TG_USER, DSL.name("CONSTRAINT_D"), new TableField[] { TgUser.TG_USER.ID }, true);
    public static final UniqueKey<TgUserRecord> CONSTRAINT_DA = Internal.createUniqueKey(TgUser.TG_USER, DSL.name("CONSTRAINT_DA"), new TableField[] { TgUser.TG_USER.CHAT_ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<LinkSubscriptionRecord, TgUserRecord> CONSTRAINT_F2 = Internal.createForeignKey(LinkSubscription.LINK_SUBSCRIPTION, DSL.name("CONSTRAINT_F2"), new TableField[] { LinkSubscription.LINK_SUBSCRIPTION.TGUSERID }, Keys.CONSTRAINT_D, new TableField[] { TgUser.TG_USER.ID }, true);
}
