/*
 * This file is generated by jOOQ.
 */

package scrapper.domains.jooq;


import javax.annotation.processing.Generated;

import scrapper.domains.jooq.tables.LinkSubscription;
import scrapper.domains.jooq.tables.TgUser;


/**
 * Convenience access to all tables in the default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>LINK_SUBSCRIPTION</code>.
     */
    public static final LinkSubscription LINK_SUBSCRIPTION = LinkSubscription.LINK_SUBSCRIPTION;

    /**
     * The table <code>TG_USER</code>.
     */
    public static final TgUser TG_USER = TgUser.TG_USER;
}
