package scrapper.Repositories;

import org.assertj.core.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.dao.DuplicateKeyException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.annotation.Rollback;
import org.springframework.transaction.annotation.Transactional;
import scrapper.IntegrationEnvironment;
import scrapper.domains.TelegramUser;

import java.util.List;
import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest
class JdbcTelegramUserDaoTest extends IntegrationEnvironment {

    @Autowired
    JdbcTelegramUserDao telegramUserDao;

    @Autowired
    JdbcTemplate jdbcTemplate;

    public static Stream<TelegramUser> getUsersForTest(){
        return Stream.of(
                new TelegramUser(1L, 211L),
                new TelegramUser(2L, 222L),
                new TelegramUser(3L, 233L)
        );
    }

    @ParameterizedTest
    @MethodSource("getUsersForTest")
    @Transactional
    @Rollback
    void AddNewUserAndGetHimByGetAllCommand(TelegramUser user) {
        //given
        telegramUserDao.add(user);

        //when
        List<TelegramUser> res = telegramUserDao.getAll();

        //then
        assertEquals(res.get(0), user);
    }

    @ParameterizedTest
    @MethodSource("getUsersForTest")
    @Transactional
    @Rollback
    void addUserAndDeleteIt(TelegramUser user){
        //given
        telegramUserDao.add(user);
        List<TelegramUser> users = telegramUserDao.getAll();
        assertEquals(users.size(), 1);

        //when
        telegramUserDao.removeByChatId(user.getChatId());
        users = telegramUserDao.getAll();

        //then
        assertEquals(users.size(), 0);
    }

    @Test
    @Transactional
    @Rollback
    void addUserWithAutoGeneratedId(){
        //given
        TelegramUser user = new TelegramUser(11L);
        //when
        var exp = telegramUserDao.add(user);
        //then
        assertEquals(exp.getChatId(), user.getChatId());
        System.out.println(exp);
    }

    @ParameterizedTest
    @MethodSource("getUsersForTest")
    @Transactional
    @Rollback
    void getByChatId(TelegramUser user){
        telegramUserDao.add(user);
        assertEquals(user.getChatId(), telegramUserDao.getByChatId(user.getChatId()).getChatId());
    }

    @ParameterizedTest
    @MethodSource("getUsersForTest")
    @Transactional
    @Rollback
    void uniqueChatIdField(TelegramUser user){
        telegramUserDao.add(user);
        try {
            telegramUserDao.add(user);
        }catch (DuplicateKeyException ex){
            assertTrue(true);
            return;
        }
        fail();
    }

}