/*
 * This file is generated by jOOQ.
 */
package scrapper.domains.jooq.tables;


import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import scrapper.domains.jooq.DefaultSchema;
import scrapper.domains.jooq.Keys;
import scrapper.domains.jooq.tables.records.TgUserRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TgUser extends TableImpl<TgUserRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>TG_USER</code>
     */
    public static final TgUser TG_USER = new TgUser();

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<TgUserRecord> getRecordType() {
        return TgUserRecord.class;
    }

    /**
     * The column <code>TG_USER.ID</code>.
     */
    public final TableField<TgUserRecord, Long> ID = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>TG_USER.CHAT_ID</code>.
     */
    public final TableField<TgUserRecord, Long> CHAT_ID = createField(DSL.name("CHAT_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    private TgUser(Name alias, Table<TgUserRecord> aliased) {
        this(alias, aliased, null);
    }

    private TgUser(Name alias, Table<TgUserRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>TG_USER</code> table reference
     */
    public TgUser(String alias) {
        this(DSL.name(alias), TG_USER);
    }

    /**
     * Create an aliased <code>TG_USER</code> table reference
     */
    public TgUser(Name alias) {
        this(alias, TG_USER);
    }

    /**
     * Create a <code>TG_USER</code> table reference
     */
    public TgUser() {
        this(DSL.name("TG_USER"), null);
    }

    public <O extends Record> TgUser(Table<O> child, ForeignKey<O, TgUserRecord> key) {
        super(child, key, TG_USER);
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    @NotNull
    public Identity<TgUserRecord, Long> getIdentity() {
        return (Identity<TgUserRecord, Long>) super.getIdentity();
    }

    @Override
    @NotNull
    public UniqueKey<TgUserRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_D;
    }

    @Override
    @NotNull
    public List<UniqueKey<TgUserRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.CONSTRAINT_DA);
    }

    @Override
    @NotNull
    public TgUser as(String alias) {
        return new TgUser(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public TgUser as(Name alias) {
        return new TgUser(alias, this);
    }

    @Override
    @NotNull
    public TgUser as(Table<?> alias) {
        return new TgUser(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public TgUser rename(String name) {
        return new TgUser(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public TgUser rename(Name name) {
        return new TgUser(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public TgUser rename(Table<?> name) {
        return new TgUser(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super Long, ? super Long, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super Long, ? super Long, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
