name: BOT CI

on:
  push:
    paths:
      - 'bot/**'
  pull_request:
    paths:
      - 'bot/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn package -pl bot -am
    - name: Show path
      run: ls -la ./bot/
    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: ${{ secrets.DOCKER_USERNAME }}/tinkoff_backend_course
        tags: latest
        registry: docker.io
        dockerfile: bot/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

